### ISSUE TITLE
Process for collecting inventory can be streamlined (takes too long)

### ISSUE THREAD

**Issue by jose-delarosa** [dell/idrac-ansible-module#17]
Currently the process for collecting system inventory takes too long as we make a Redfish call for each inventory element we specify. So per server, we make 12-15 calls. We should make only one Redfish call, however doing do we will have to parse the returned information differently. Best approach?

**Comment by sujithshankar** [comment]
For every Redfish call (GET/POST etc.), we have access credentials as payload and authentication to be done. Do you think this approach might contribute to the delay?
Can we make a session/cookie kind-of approach in python?

**Comment by jose-delarosa** [comment]
Problem is that for each inventory item, we make a GET/POST request and then process the result (we go through a loop). I think a better approach is to just get all inventory items in one GET/POST call and then sort out all results afterwards. One possible implementation approach is to get all results in JSON files, and then in a separate action (via a script?) extract all the relevant information from the JSON files.

**Comment by jose-delarosa** [comment]
Addressed in https://github.com/dell/idrac-ansible-module/commit/623b6354cc9cc2459187b56fc7e41788a5167653
