### ISSUE TITLE
Handle failure codes as failures

### ISSUE THREAD

**Issue by wrouesnel** [dell/idrac-ansible-module#20]
It looks like a lot of failure codes aren't picked up as module failures, and thus treat the host as "ok" despite nothing working - i.e. this 401 error shows as green:
`ok: [fresh.nodes -> provisioning] => {"changed": false, "failed": false, "result": 401}`

**Comment by jose-delarosa** [comment]
What playbook were you running? I agree error detection can be improved. Pull requests are welcome :)

**Comment by wrouesnel** [comment]
I should have something later :)

**Comment by jose-delarosa** [comment]
Working on catching failures, should have it committed by end of day 10.02

**Comment by jose-delarosa** [comment]
Try again with latest commit. All existing functions now handle most error codes correctly.

**Comment by jose-delarosa** [comment]
If problem persists, please reopen.
