### ISSUE TITLE
Ability to upgrade firmware on 13th gen/iDRAC 8

### ISSUE THREAD

**Issue by alistarle** [dell/idrac-ansible-module#30]
Hi,

I see the redfish API and your scripts will make my work easier but it seems that redfish are not fully supported by my hardware, only a limited set of API endpoint are visible on my iDRAC.

It seems on 13th gen R630 host (with iDRAC 8, firmware 2.50.50.50), the /redfish/v1/UpdateService/FirmwareInventory/ is not available. 

Can you confirm, as indicated on your documentation, that firmware upgrade via redfish API is available on 13th gen/iDRAC 8 ?

btw redfish and your ansible playbook is a great work, keep going ;)

**Comment by jose-delarosa** [comment]
You are correct FW upgrade is only available with 14G. No word on if/when it might be supported with 13G/12G. Will update the documentation accordingly.

Thanks for your support, there are some more features I will add in coming week, let me know if there is anything obvious that is missing. And as always, contributions are welcome!
