### ISSUE TITLE
failed to get firmwares inventory

### ISSUE THREAD

**Issue by survietamine** [dell/idrac-ansible-module#52]
Hello, running get_firmware_inventory.yml against a 13g (r630) server with latest firmware (2.50.50.50), it failed.
Others playbooks like get_system_inventory.yml worked fine. So, did I missed something? Do I  have to enable some config in iDRAC?

```
fatal: [myserver.example.net -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "FWPath": null, 
            "InstallOption": null, 
            "Model": null, 
            "baseuri": "myserver.rmcp.example.net", 
            "bios_attr_name": null, 
            "bios_attr_value": null, 
            "bootdevice": null, 
            "category": "Update", 
            "command": "GetFirmwareInventory", 
            "hostname": null, 
            "mgr_attr_name": null, 
            "mgr_attr_value": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "scpfile": null, 
            "sharehost": null, 
            "sharename": null, 
            "sharepswd": null, 
            "shareuser": null, 
            "user": "root", 
            "userid": null, 
            "username": null, 
            "userpswd": null, 
            "userrole": null
        }
    }, 
    "msg": "UpdateService does not exist"
}
...ignoring

```

**Comment by prabhakarpujeri** [comment]
@survietamine  13G Servers does not  support firmware update

**Comment by survietamine** [comment]
@prabhakarpujeri thanks for your answer!
I don't want to update my firmwares. Since that playbook is named get_firmware_inventory, should I still be able to list my firmwares from all my iDRAC using redfish?

**Comment by prabhakarpujeri** [comment]
even inventory collection API's are not available for 13G

**Comment by survietamine** [comment]
@prabhakarpujeri uffff, that redfish thing looks very new. So 14G is the way to go to nicely play with redfish and ansible?

**Comment by survietamine** [comment]
OK, I've seen in the README that Inventory won't work on all platforms.
But why didn't I get what is mentionned in that example:

> fatal: [r630 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Not supported on this platform"}
> ...ignoring

**Comment by jose-delarosa** [comment]
survietamine, I just pushed a lot of new updates yesterday in an effort to make the module more vendor-neutral, so error messages are a bit more generic. I need to update the README, expect updates today or tomorrow.

**Comment by jose-delarosa** [comment]
@survietamine Updated the README with proper error message when getting firmware inventory. But as @prabhakarpujeri mentioned, firmware inventory and firmware upgrade are currently only supported in 14G PowerEdge servers.

**Comment by survietamine** [comment]
Thank you very much both guys :p

Le 12 févr. 2018 10:20 PM, "Jose Delarosa" <notifications@github.com> a
écrit :

**Comment by jose-delarosa** [comment]
Closing, if you have other questions please open another issue.
